// lib/mockData.ts
import type {
  Stat,
  SalesOrder,
  InventoryItem,
  Customer,
  Product,
  Warehouse,
  Driver,
  SOItem,
  InvoiceProduct,
  FakturPajakInvoice,
  FakturPajakItem,
  KodeTransaksi,
  PaymentInvoice,
  PaymentMethod,
  InventoryProduct,
  WAMessage,
  RevenueData,
  ARAgingData,
  Account,
  Business,
} from '@/types'

export const businesses = [
  {
    id: '1',
    name: 'Vila Melati Canggu',
    type: 'penginapan',
    area: 'Canggu',
    emoji: '🏡',
    color: '#2d6a4f',
  },
  {
    id: '2',
    name: 'UD Sari Daging Bali',
    type: 'supplier',
    area: 'Denpasar',
    emoji: '🥩',
    color: '#e07b39',
  },
  {
    id: '3',
    name: 'Warung Bu Ketut',
    type: 'kuliner',
    area: 'Ubud',
    emoji: '🍽️',
    color: '#c9733a',
  },
]

export const statsData: Record<string, Stat[]> = {
  penginapan: [
    {
      label: 'Tamu Menginap',
      value: '8',
      unit: 'kamar',
      change: '+2',
      up: true,
      icon: 'home',
    },
    {
      label: 'Check-in Hari Ini',
      value: '3',
      unit: 'tamu',
      change: 'sama',
      up: null,
      icon: 'user',
    },
    {
      label: 'Revenue Bulan Ini',
      value: '24.6',
      unit: 'juta',
      change: '+18%',
      up: true,
      icon: 'chart',
    },
    {
      label: 'Belum Bayar',
      value: '4',
      unit: 'booking',
      change: '-1',
      up: true,
      icon: 'receipt',
    },
  ],
  supplier: [
    {
      label: 'Order Hari Ini',
      value: '12',
      unit: 'SO',
      change: '+3',
      up: true,
      icon: 'shop',
    },
    {
      label: 'Revenue Bulan Ini',
      value: '68.4',
      unit: 'juta',
      change: '+22%',
      up: true,
      icon: 'chart',
    },
    {
      label: 'Piutang Belum Bayar',
      value: '14.2',
      unit: 'juta',
      change: '-2.1jt',
      up: true,
      icon: 'receipt',
    },
    {
      label: 'Stok Hampir Habis',
      value: '3',
      unit: 'produk',
      change: '+1',
      up: false,
      icon: 'box',
    },
  ],
  kuliner: [
    {
      label: 'Order Hari Ini',
      value: '47',
      unit: 'pesanan',
      change: '+12',
      up: true,
      icon: 'shop',
    },
    {
      label: 'Revenue Hari Ini',
      value: '1.85',
      unit: 'juta',
      change: '+15%',
      up: true,
      icon: 'chart',
    },
    {
      label: 'WA Order Masuk',
      value: '9',
      unit: 'baru',
      change: '+3',
      up: true,
      icon: 'chat',
    },
    {
      label: 'Stok Hampir Habis',
      value: '5',
      unit: 'item',
      change: '+2',
      up: false,
      icon: 'box',
    },
  ],
}

export const soData: SalesOrder[] = [
  {
    id: 'SO-2026-0042',
    customer: 'RM Padang Jaya',
    date: '22 Mar',
    items: 4,
    total: 1890000,
    status: 'confirmed',
    payment: 'unpaid',
  },
  {
    id: 'SO-2026-0041',
    customer: 'Hotel Melati Seminyak',
    date: '22 Mar',
    items: 7,
    total: 4560000,
    status: 'delivered',
    payment: 'paid',
  },
  {
    id: 'SO-2026-0040',
    customer: 'Warung Nasi Bu Wayan',
    date: '21 Mar',
    items: 3,
    total: 875000,
    status: 'delivered',
    payment: 'partial',
  },
  {
    id: 'SO-2026-0039',
    customer: 'Bali Belly Restaurant',
    date: '21 Mar',
    items: 5,
    total: 2340000,
    status: 'confirmed',
    payment: 'dp',
  },
  {
    id: 'SO-2026-0038',
    customer: 'Sunset Grill Canggu',
    date: '20 Mar',
    items: 6,
    total: 3120000,
    status: 'delivered',
    payment: 'paid',
  },
]

export const customers: Customer[] = [
  {
    id: 'c1',
    code: 'CUST-001',
    name: 'RM Padang Jaya',
    type: 'wholesale',
    phone: '08123456789',
    address: 'Jl. Sunset Road No.12, Seminyak',
    area: 'Seminyak',
    npwp: '01.234.567.8-901.000',
    is_pkp: true,
    payment_terms: 14,
    price_group: 'Harga Grosir',
    outstanding_ar: 3200000,
  },
  {
    id: 'c2',
    code: 'CUST-002',
    name: 'Hotel Melati Seminyak',
    type: 'premium',
    phone: '08234567890',
    address: 'Jl. Laksmana No.7, Seminyak',
    area: 'Seminyak',
    npwp: '02.345.678.9-012.000',
    is_pkp: true,
    payment_terms: 30,
    price_group: 'Harga Hotel',
    outstanding_ar: 0,
  },
  {
    id: 'c3',
    code: 'CUST-003',
    name: 'Warung Bu Wayan',
    type: 'retail',
    phone: '08345678901',
    address: 'Jl. Penestanan, Ubud',
    area: 'Ubud',
    npwp: '',
    is_pkp: false,
    payment_terms: 7,
    price_group: 'Harga Retail',
    outstanding_ar: 875000,
  },
  {
    id: 'c4',
    code: 'CUST-004',
    name: 'Bali Belly Restaurant',
    type: 'wholesale',
    phone: '08456789012',
    address: 'Jl. Drupadi No.3, Seminyak',
    area: 'Seminyak',
    npwp: '03.456.789.0-123.000',
    is_pkp: true,
    payment_terms: 14,
    price_group: 'Harga Grosir',
    outstanding_ar: 2340000,
  },
  {
    id: 'c5',
    code: 'CUST-005',
    name: 'Sunset Grill Canggu',
    type: 'wholesale',
    phone: '08567890123',
    address: 'Jl. Batu Bolong No.88, Canggu',
    area: 'Canggu',
    npwp: '04.567.890.1-234.000',
    is_pkp: true,
    payment_terms: 14,
    price_group: 'Harga Grosir',
    outstanding_ar: 0,
  },
]

export const products: Product[] = [
  {
    id: 'p1',
    sku: 'SPI-001',
    name: 'Daging Sapi Has Dalam',
    cat: 'Daging Sapi',
    uom: 'kg',
    base_price: 145000,
    prices: {
      'Harga Grosir': 138000,
      'Harga Hotel': 135000,
      'Harga Retail': 145000,
    },
    stock: 45.5,
    tax_rate: 0,
  },
  {
    id: 'p2',
    sku: 'SPI-002',
    name: 'Iga Sapi Premium',
    cat: 'Daging Sapi',
    uom: 'kg',
    base_price: 128000,
    prices: {
      'Harga Grosir': 122000,
      'Harga Hotel': 120000,
      'Harga Retail': 128000,
    },
    stock: 22.0,
    tax_rate: 0,
  },
  {
    id: 'p3',
    sku: 'SPI-003',
    name: 'Daging Sapi Giling',
    cat: 'Daging Sapi',
    uom: 'kg',
    base_price: 115000,
    prices: {
      'Harga Grosir': 110000,
      'Harga Hotel': 108000,
      'Harga Retail': 115000,
    },
    stock: 18.0,
    tax_rate: 0,
  },
  {
    id: 'p4',
    sku: 'AYM-001',
    name: 'Ayam Broiler Utuh',
    cat: 'Unggas',
    uom: 'kg',
    base_price: 32000,
    prices: {
      'Harga Grosir': 30000,
      'Harga Hotel': 29000,
      'Harga Retail': 32000,
    },
    stock: 8.0,
    tax_rate: 0,
  },
  {
    id: 'p5',
    sku: 'BBK-001',
    name: 'Daging Bebek Segar',
    cat: 'Unggas',
    uom: 'kg',
    base_price: 65000,
    prices: {
      'Harga Grosir': 62000,
      'Harga Hotel': 60000,
      'Harga Retail': 65000,
    },
    stock: 3.5,
    tax_rate: 0,
  },
  {
    id: 'p6',
    sku: 'IKN-001',
    name: 'Ikan Tuna Segar',
    cat: 'Seafood',
    uom: 'kg',
    base_price: 88000,
    prices: {
      'Harga Grosir': 84000,
      'Harga Hotel': 82000,
      'Harga Retail': 88000,
    },
    stock: 28.0,
    tax_rate: 0,
  },
  {
    id: 'p7',
    sku: 'UDG-001',
    name: 'Udang Vannamei',
    cat: 'Seafood',
    uom: 'kg',
    base_price: 95000,
    prices: {
      'Harga Grosir': 90000,
      'Harga Hotel': 88000,
      'Harga Retail': 95000,
    },
    stock: 18.0,
    tax_rate: 0,
  },
  {
    id: 'p8',
    sku: 'CMI-001',
    name: 'Cumi-cumi Segar',
    cat: 'Seafood',
    uom: 'kg',
    base_price: 72000,
    prices: {
      'Harga Grosir': 68000,
      'Harga Hotel': 66000,
      'Harga Retail': 72000,
    },
    stock: 6.0,
    tax_rate: 0,
  },
  {
    id: 'p9',
    sku: 'OLH-001',
    name: 'Sosis Sapi Premium',
    cat: 'Olahan',
    uom: 'pack',
    base_price: 45000,
    prices: {
      'Harga Grosir': 42000,
      'Harga Hotel': 41000,
      'Harga Retail': 45000,
    },
    stock: 40,
    tax_rate: 11,
  },
  {
    id: 'p10',
    sku: 'OLH-002',
    name: 'Bakso Sapi Isi 50',
    cat: 'Olahan',
    uom: 'pack',
    base_price: 38000,
    prices: {
      'Harga Grosir': 35000,
      'Harga Hotel': 34000,
      'Harga Retail': 38000,
    },
    stock: 35,
    tax_rate: 11,
  },
]

export const warehouses: Warehouse[] = [
  { id: 'w1', name: 'Gudang Utama', code: 'GDG-01' },
  { id: 'w2', name: 'Cold Storage', code: 'CLD-01' },
]

export const drivers: Driver[] = [
  {
    id: '1',
    name: 'Wayan Suardika',
    vehicle: 'Toyota Hiace · DK 1234 AB',
    phone: '08111222333',
  },
  {
    id: '2',
    name: 'Made Wirawan',
    vehicle: 'Pickup Mitsubishi · DK 5678 CD',
    phone: '08222333444',
  },
]

export const soItemsExample: SOItem[] = [
  { id: 'a', sku: 'SPI-001', name: 'Daging Sapi Has Dalam', uom: 'kg', qty_so: 10, price: 138000 },
  { id: 'b', sku: 'SPI-002', name: 'Iga Sapi Premium', uom: 'kg', qty_so: 5, price: 122000 },
  { id: 'c', sku: 'IKN-001', name: 'Ikan Tuna Segar', uom: 'kg', qty_so: 8, price: 84000 },
  { id: 'd', sku: 'UDG-001', name: 'Udang Vannamei', uom: 'kg', qty_so: 3, price: 90000 },
]

export const inventoryData: InventoryItem[] = [
  {
    id: 1,
    sku: 'SPI-001',
    name: 'Daging Sapi Has Dalam',
    category: 'Daging Sapi',
    stock: 45.5,
    uom: 'kg',
    min: 20,
    price: 145000,
    status: 'ok',
  },
  {
    id: 2,
    sku: 'AYM-001',
    name: 'Ayam Broiler Utuh',
    category: 'Unggas',
    stock: 12.0,
    uom: 'kg',
    min: 15,
    price: 32000,
    status: 'low',
  },
  {
    id: 3,
    sku: 'IKN-001',
    name: 'Ikan Tuna Segar',
    category: 'Seafood',
    stock: 28.0,
    uom: 'kg',
    min: 10,
    price: 88000,
    status: 'ok',
  },
  {
    id: 4,
    sku: 'BBK-001',
    name: 'Daging Bebek',
    category: 'Unggas',
    stock: 3.5,
    uom: 'kg',
    min: 10,
    price: 65000,
    status: 'critical',
  },
  {
    id: 5,
    sku: 'UDG-001',
    name: 'Udang Vannamei',
    category: 'Seafood',
    stock: 18.0,
    uom: 'kg',
    min: 8,
    price: 95000,
    status: 'ok',
  },
  {
    id: 6,
    sku: 'SPI-002',
    name: 'Iga Sapi',
    category: 'Daging Sapi',
    stock: 22.0,
    uom: 'kg',
    min: 15,
    price: 128000,
    status: 'ok',
  },
]

export const businessData = {
  name: 'UD Sari Daging Bali',
  legal: 'UD Sari Daging Bali',
  addr: 'Jl. Gatot Subroto No. 45, Denpasar Selatan, Bali 80239',
  phone: '0361-234567',
  wa: '08123456789',
  email: 'info@udsamridagingbali.com',
  npwp: '01.234.567.8-901.000',
  bank: 'BCA',
  account: '1234567890',
  holder: 'UD Sari Daging Bali',
  logo: null,
}

export const invoiceProducts: InvoiceProduct[] = [
  { id: 'p1', sku: 'SPI-001', name: 'Daging Sapi Has Dalam', uom: 'kg', price: 138000, tax: 0 },
  { id: 'p2', sku: 'SPI-002', name: 'Iga Sapi Premium', uom: 'kg', price: 122000, tax: 0 },
  { id: 'p3', sku: 'IKN-001', name: 'Ikan Tuna Segar', uom: 'kg', price: 84000, tax: 0 },
  { id: 'p4', sku: 'UDG-001', name: 'Udang Vannamei', uom: 'kg', price: 90000, tax: 0 },
  { id: 'p5', sku: 'AYM-001', name: 'Ayam Broiler Utuh', uom: 'kg', price: 29000, tax: 0 },
  { id: 'p6', sku: 'OLH-001', name: 'Sosis Sapi Premium', uom: 'pack', price: 42000, tax: 11 },
  { id: 'p7', sku: 'OLH-002', name: 'Bakso Sapi Isi 50', uom: 'pack', price: 35000, tax: 11 },
]

export const businessSeller = {
  npwp: '01.234.567.8-901.000',
  name: 'UD SARI DAGING BALI',
  addr: 'JL. GATOT SUBROTO NO. 45, DENPASAR SELATAN, BALI 80239',
  is_pkp: true,
  pkp_date: '2023-01-15',
}

export const fakturPajakInvoices: FakturPajakInvoice[] = [
  {
    id: 'inv1',
    number: 'INV-2026-0019',
    date: '2026-03-22',
    customer_id: 'c1',
    subtotal: 1966000,
    disc: 98300,
    tax_base: 1867700,
    ppn: 205447,
    total: 2073147,
  },
  {
    id: 'inv2',
    number: 'INV-2026-0018',
    date: '2026-03-21',
    customer_id: 'c2',
    subtotal: 4560000,
    disc: 0,
    tax_base: 4560000,
    ppn: 501600,
    total: 5061600,
  },
]

export const fakturPajakItems: Record<string, FakturPajakItem[]> = {
  inv1: [
    {
      name: 'Daging Sapi Has Dalam',
      qty: 10,
      uom: 'KG',
      harga: 138000,
      disc_pct: 0,
      ppn_pct: 0,
    },
    {
      name: 'Iga Sapi Premium',
      qty: 5,
      uom: 'KG',
      harga: 122000,
      disc_pct: 0,
      ppn_pct: 0,
    },
    {
      name: 'Sosis Sapi Premium',
      qty: 6,
      uom: 'PACK',
      harga: 42000,
      disc_pct: 5,
      ppn_pct: 11,
    },
  ],
  inv2: [
    {
      name: 'Daging Sapi Has Dalam',
      qty: 20,
      uom: 'KG',
      harga: 135000,
      disc_pct: 0,
      ppn_pct: 0,
    },
    {
      name: 'Ayam Broiler Utuh',
      qty: 15,
      uom: 'KG',
      harga: 29000,
      disc_pct: 0,
      ppn_pct: 0,
    },
    {
      name: 'Bakso Sapi Isi 50',
      qty: 20,
      uom: 'PACK',
      harga: 34000,
      disc_pct: 0,
      ppn_pct: 11,
    },
  ],
}

export const kodeTransaksi: KodeTransaksi[] = [
  { kode: '01', label: 'Kepada Pihak yang Bukan Pemungut PPN' },
  { kode: '02', label: 'Kepada Pemungut Bendaharawan' },
  { kode: '03', label: 'Kepada Pemungut Selain Bendaharawan' },
  { kode: '04', label: 'DPP Nilai Lain' },
  { kode: '07', label: 'PPN Tidak Dipungut' },
  { kode: '08', label: 'PPN Dibebaskan' },
]

export const paymentInvoices: PaymentInvoice[] = [
  {
    id: 'i1',
    number: 'INV-2026-0019',
    date: '2026-03-22',
    due: '2026-04-05',
    customer: 'RM Padang Jaya',
    customer_id: 'c1',
    phone: '08123456789',
    total: 2073147,
    paid: 0,
    status: 'unpaid',
  },
  {
    id: 'i2',
    number: 'INV-2026-0018',
    date: '2026-03-21',
    due: '2026-04-20',
    customer: 'Hotel Melati Seminyak',
    customer_id: 'c2',
    phone: '08234567890',
    total: 5061600,
    paid: 2500000,
    status: 'partial',
  },
  {
    id: 'i3',
    number: 'INV-2026-0017',
    date: '2026-03-20',
    due: '2026-03-27',
    customer: 'Bali Belly Restaurant',
    customer_id: 'c4',
    phone: '08456789012',
    total: 1890000,
    paid: 0,
    status: 'unpaid',
    overdue: true,
  },
  {
    id: 'i4',
    number: 'INV-2026-0016',
    date: '2026-03-18',
    due: '2026-04-01',
    customer: 'Warung Bu Wayan',
    customer_id: 'c3',
    phone: '08345678901',
    total: 875000,
    paid: 500000,
    status: 'partial',
  },
  {
    id: 'i5',
    number: 'INV-2026-0015',
    date: '2026-03-15',
    due: '2026-03-29',
    customer: 'Sunset Grill Canggu',
    customer_id: 'c5',
    phone: '08567890123',
    total: 3120000,
    paid: 3120000,
    status: 'paid',
  },
]

export const paymentMethods: PaymentMethod[] = [
  { id: 'transfer', label: 'Transfer Bank', icon: '🏦', hint: 'BCA / BNI / Mandiri / dll' },
  { id: 'cash', label: 'Tunai (Cash)', icon: '💵', hint: 'Bayar langsung di tempat' },
  { id: 'qris', label: 'QRIS', icon: '📱', hint: 'Scan QR Code' },
  { id: 'giro', label: 'Cek / Giro', icon: '📄', hint: 'Cek atau bilyet giro' },
]

export const banks = [
  'BCA',
  'BNI',
  'BRI',
  'Mandiri',
  'CIMB Niaga',
  'Danamon',
  'Permata',
  'BSI',
  'Jenius',
  'GoPay',
  'OVO',
  'Dana',
]

// ============ INVENTORY PRODUCTS ============
export const inventoryProducts: InventoryProduct[] = [
  {
    id: 'p1',
    sku: 'SPI-001',
    name: 'Daging Sapi Has Dalam',
    category: 'Daging Sapi',
    stock: 45.5,
    uom: 'kg',
    min_stock: 20,
    price: 145000,
    status: 'ok',
  },
  {
    id: 'p2',
    sku: 'AYM-001',
    name: 'Ayam Broiler Utuh',
    category: 'Unggas',
    stock: 12.0,
    uom: 'kg',
    min_stock: 15,
    price: 32000,
    status: 'low',
  },
  {
    id: 'p3',
    sku: 'IKN-001',
    name: 'Ikan Tuna Segar',
    category: 'Seafood',
    stock: 28.0,
    uom: 'kg',
    min_stock: 10,
    price: 88000,
    status: 'ok',
  },
  {
    id: 'p4',
    sku: 'BBK-001',
    name: 'Daging Bebek',
    category: 'Unggas',
    stock: 3.5,
    uom: 'kg',
    min_stock: 10,
    price: 65000,
    status: 'critical',
  },
  {
    id: 'p5',
    sku: 'UDG-001',
    name: 'Udang Vannamei',
    category: 'Seafood',
    stock: 18.0,
    uom: 'kg',
    min_stock: 8,
    price: 95000,
    status: 'ok',
  },
  {
    id: 'p6',
    sku: 'SPI-002',
    name: 'Iga Sapi',
    category: 'Daging Sapi',
    stock: 22.0,
    uom: 'kg',
    min_stock: 15,
    price: 128000,
    status: 'ok',
  },
]

// ============ WA MESSAGES ============
export const waMessages: WAMessage[] = [
  {
    id: 'w1',
    phone: '628123456789',
    name: 'Pak Agus (RM Padang)',
    time: '08:42',
    msg: '1=10kg, 3=5kg',
    direction: 'in',
    flow: 'catalog_code',
    status: 'completed',
  },
  {
    id: 'w2',
    phone: '628234567890',
    name: 'Bu Sarah (Hotel Melati)',
    time: '09:15',
    msg: 'minta 20kg has dalam besok pagi',
    direction: 'in',
    flow: 'catalog_code',
    status: 'completed',
  },
  {
    id: 'w3',
    phone: '628345678901',
    name: 'Unknown (+6283456)',
    time: '10:30',
    msg: 'halo ada daging sapi?',
    direction: 'in',
    flow: 'guided',
    status: 'active',
  },
  {
    id: 'w4',
    phone: '628456789012',
    name: 'Pak Budi (Bali Belly)',
    time: '11:02',
    msg: 'order seperti biasa ya',
    direction: 'in',
    flow: 'catalog_code',
    status: 'completed',
  },
]

// ============ REVENUE DATA ============
export const revenueData: RevenueData[] = [
  { month: 'Jan', amount: 42 },
  { month: 'Feb', amount: 38 },
  { month: 'Mar', amount: 55 },
  { month: 'Apr', amount: 48 },
  { month: 'Mei', amount: 62 },
  { month: 'Jun', amount: 58 },
  { month: 'Jul', amount: 71 },
  { month: 'Agt', amount: 66 },
  { month: 'Sep', amount: 75 },
  { month: 'Okt', amount: 68 },
  { month: 'Nov', amount: 80 },
  { month: 'Des', amount: 73 },
]

// ============ AR AGING DATA ============
export const arAgingData: ARAgingData[] = [
  { period: 'Current', amount: 5200000, count: 2 },
  { period: '1-30 Hari', amount: 4800000, count: 3 },
  { period: '31-60 Hari', amount: 2800000, count: 1 },
  { period: '> 60 Hari', amount: 1400000, count: 1 },
]

// ============ ACCOUNTING - ACCOUNTS ============
export const chartOfAccounts: Account[] = [
  { id: 'a1', code: '1100', name: 'Kas', type: 'asset', balance: 25000000 },
  { id: 'a2', code: '1200', name: 'Bank', type: 'asset', balance: 150000000 },
  { id: 'a3', code: '1300', name: 'Piutang Usaha', type: 'asset', balance: 14200000 },
  { id: 'a4', code: '1400', name: 'Persediaan', type: 'asset', balance: 45000000 },
  { id: 'a5', code: '2100', name: 'Hutang Usaha', type: 'liability', balance: 8500000 },
  { id: 'a6', code: '2200', name: 'Hutang Pajak', type: 'liability', balance: 2100000 },
  { id: 'a7', code: '3100', name: 'Modal Usaha', type: 'equity', balance: 200000000 },
  { id: 'a8', code: '4100', name: 'Penjualan Barang', type: 'income', balance: 68400000 },
  { id: 'a9', code: '5100', name: 'Harga Pokok Penjualan', type: 'expense', balance: 48200000 },
  { id: 'a10', code: '5200', name: 'Beban Operasional', type: 'expense', balance: 5000000 },
]

// ============ BUSINESSES ============
export const businessList: Business[] = [
  {
    id: 'b1',
    name: 'UD Sari Daging Bali',
    type: 'supplier',
    emoji: '🥩',
    address: 'Jl. Gatot Subroto No. 45, Denpasar',
    phone: '0361-234567',
    email: 'info@udsamridagingbali.com',
    npwp: '01.234.567.8-901.000',
    area: 'Denpasar',
    created_at: '2025-01-15',
  },
  {
    id: 'b2',
    name: 'Vila Melati Canggu',
    type: 'penginapan',
    emoji: '🏡',
    address: 'Jl. Pantai Canggu No. 88, Canggu',
    phone: '0361-987654',
    email: 'booking@vilamelati.com',
    npwp: '02.345.678.9-012.000',
    area: 'Canggu',
    created_at: '2025-02-10',
  },
  {
    id: 'b3',
    name: 'Warung Bu Ketut',
    type: 'kuliner',
    emoji: '🍽️',
    address: 'Jl. Raya Ubud, Ubud',
    phone: '0361-555666',
    area: 'Ubud',
    created_at: '2025-03-01',
  },
]

// ============ PRODUCTS LIST (untuk menu Produk) ============
export const productsList = [
  {
    id: 'p1',
    sku: 'SPI-001',
    name: 'Daging Sapi Has Dalam',
    category: 'Daging Sapi',
    description: 'Daging sapi segar berkualitas premium',
    price: 145000,
    cost: 120000,
    uom: 'kg',
    tax_rate: 0,
    active: true,
  },
  {
    id: 'p2',
    sku: 'OLH-001',
    name: 'Sosis Sapi Premium',
    category: 'Olahan',
    description: 'Sosis daging sapi asli tanpa pengawet',
    price: 45000,
    cost: 30000,
    uom: 'pack',
    tax_rate: 11,
    active: true,
  },
  {
    id: 'p3',
    sku: 'OLH-002',
    name: 'Bakso Sapi Isi 50',
    category: 'Olahan',
    description: 'Bola daging sapi premium',
    price: 38000,
    cost: 25000,
    uom: 'pack',
    tax_rate: 11,
    active: true,
  },
]